nodeLinker: hoisted

# 可选：控制 hoisting 范围（v11.5.0+）
hoistingLimits: none # none | workspaces | dependencies

# 允许 exotic 子依赖（解决 @electron/node-gyp 问题）
blockExoticSubdeps: false

# 依赖覆盖
overrides:
  eslint-plugin-react-compiler>zod: '^3.24.4'
  ssh2>cpu-features: 'npm:empty-npm-package@1.0.0'

allowBuilds:
  '@swc/core': true
  cpu-features: true
  fs-xattr: true
  macos-alias: true
  ssh2: true
