export const ERROR_CODE = {
  CONN_FAILED: 'CONN_FAILED',
  CONN_NOT_FOUND: 'CONN_NOT_FOUND',
  AUTH_ERROR: 'AUTH_ERROR',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_CLOSING: 'SESSION_CLOSING',
  DISCONNECT_ERROR: 'DISCONNECT_ERROR',
  CLEANUP_ERROR: 'CLEANUP_ERROR',

  LIST_ERROR: 'LIST_ERROR',
  LIST_TIMEOUT: 'LIST_TIMEOUT',
  LIST_ABORTED: 'LIST_ABORTED',
  LIST_FAILED: 'LIST_FAILED',

  MKDIR_ERROR: 'MKDIR_ERROR',
  MKDIR_TIMEOUT: 'MKDIR_TIMEOUT',
  MKDIR_ABORTED: 'MKDIR_ABORTED',

  RENAME_ERROR: 'RENAME_ERROR',
  RENAME_TIMEOUT: 'RENAME_TIMEOUT',
  RENAME_ABORTED: 'RENAME_ABORTED',

  DELETE_ERROR: 'DELETE_ERROR',
  DELETE_TIMEOUT: 'DELETE_TIMEOUT',
  DELETE_ABORTED: 'DELETE_ABORTED',

  COPY_ERROR: 'COPY_ERROR',
  COPY_ABORTED: 'COPY_ABORTED',

  MOVE_ERROR: 'MOVE_ERROR',
  MOVE_ABORTED: 'MOVE_ABORTED',

  UPLOAD_IN_PROGRESS: 'UPLOAD_IN_PROGRESS',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  UPLOAD_ABORTED: 'UPLOAD_ABORTED',
  UPLOAD_DUPLICATE: 'UPLOAD_DUPLICATE',
  CONFLICT_CHECK_ERROR: 'CONFLICT_CHECK_ERROR',

  DOWNLOAD_ERROR: 'DOWNLOAD_ERROR',
  DOWNLOAD_ABORTED: 'DOWNLOAD_ABORTED',

  PING_ERROR: 'PING_ERROR',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  PATH_ERROR: 'PATH_ERROR',

  HOST_KEY_ERROR: 'HOST_KEY_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  DIALOG_ERROR: 'DIALOG_ERROR',

  ENCRYPT_UNAVAILABLE: 'ENCRYPT_UNAVAILABLE',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  DECRYPT_FORMAT_ERROR: 'DECRYPT_FORMAT_ERROR',
  DECRYPT_UNAVAILABLE: 'DECRYPT_UNAVAILABLE',
  HMAC_MISMATCH: 'HMAC_MISMATCH',
  DECRYPTION_ERROR: 'DECRYPTION_ERROR',

  INVALID_STATE: 'INVALID_STATE',
  SELF_CONTAINED: 'SELF_CONTAINED',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]

export const ERROR_MESSAGE = {
  UPLOAD_ABORTED: 'Upload was aborted',
  DOWNLOAD_ABORTED: 'Download was aborted',
  OPERATION_ABORTED: 'Operation was aborted',
  OPERATION_ALREADY_ABORTED: 'Operation was already aborted',
} as const
